name: Build and Test FirmWire

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Panda
        uses: actions/checkout@v2
        with:
          repository: FirmWire/panda
          path: panda/
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/build-push-action
      - name: Build FirmWire
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: firmwire:latest
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      - name: Basic FirmWire execution
        run: docker run -v ${{ github.workspace }}:/firmwire firmwire:latest ./firmwire.py --help

      - name: Build ModKit
        run: docker run -v ${{ github.workspace }}:/firmwire firmwire:latest make -C modkit/
